title: "Low, Jiat Zin"
# logo: 
linkedin: "https://www.linkedin.com/in/jiatzin-low-9b832a290/"
email: "mailto:lowjiatzzz@gmail.com"
github: "https://github.com/yourusername"
theme: jekyll-theme-minimal
